//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLVerifier.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSLVerifier.Core.Data.HtmlTemplate", typeof(HtmlTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; class=&quot;collapsible collapsible2&quot;&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/button&gt;
        ///        &lt;div class=&quot;content&quot;&gt;{1}&lt;/div&gt;.
        /// </summary>
        internal static string HTML_CERT_CHAIN {
            get {
                return ResourceManager.GetString("HTML_CERT_CHAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///                &lt;h3&gt;Certificate #{0}&lt;/h3&gt;
        ///                &lt;table class=&quot;table&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;td class=&quot;bold&quot;&gt;Subject&lt;/td&gt;
        ///                            &lt;td&gt;{1}&lt;/td&gt;
        ///                        &lt;/tr&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;td class=&quot;bold&quot;&gt;Alternative Names&lt;/td&gt;
        ///                            &lt;td&gt;{2}&lt;/td&gt;
        ///                        &lt;/tr&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_CERT_DUMP {
            get {
                return ResourceManager.GetString("HTML_CERT_DUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;default&quot;&gt;Total: {0}&lt;/span&gt;|
        ///                    &lt;span&gt;Unknown: {1}&lt;/span&gt;|
        ///                    &lt;span class=&quot;success&quot;&gt;Valid: {2}&lt;/span&gt;|
        ///                    &lt;span class=&quot;warning&quot;&gt;Warning: {3}&lt;/span&gt;|
        ///                    &lt;span class=&quot;danger&quot;&gt;Failed: {4}&lt;/span&gt;.
        /// </summary>
        internal static string HTML_COUNT_SUMMARY {
            get {
                return ResourceManager.GetString("HTML_COUNT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; class=&quot;collapsible collapsible1&quot;&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/button&gt;
        ///    &lt;div class=&quot;content&quot;&gt;
        ///        &lt;p&gt;Tables below outline certificate chains for all automatic redirects.&lt;/p&gt;
        ///        {1}
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string HTML_ENTRY_CERT_ALL {
            get {
                return ResourceManager.GetString("HTML_ENTRY_CERT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;{0}&quot;&gt;
        ///                &lt;td width=&quot;16px&quot;&gt;
        ///                    &lt;img src=&quot;data:image/png;base64, {1}&quot; alt=&quot;&quot; /&gt;
        ///                &lt;/td&gt;
        ///                &lt;td&gt;{2}&lt;/td&gt;
        ///                &lt;td class=&quot;center&quot;&gt;{3}&lt;/td&gt;
        ///                &lt;td&gt;{4}&lt;/td&gt;
        ///                &lt;td class=&quot;center&quot;&gt;{5}&lt;/td&gt;
        ///                &lt;td class=&quot;center&quot;&gt;{6}&lt;/td&gt;
        ///                &lt;td class=&quot;center&quot;&gt;{7}&lt;/td&gt;
        ///            &lt;/tr&gt;.
        /// </summary>
        internal static string HTML_MAIN_ROW {
            get {
                return ResourceManager.GetString("HTML_MAIN_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///    &lt;title&gt;SSL Certificate Verifier Report&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @media print {{
        ///            .cert-dump {{
        ///            }}
        ///        }}
        ///
        ///        body {{
        ///            font: 11pt &quot;Arial&quot;;
        ///        }}
        ///
        ///        pre {{
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_REPORT {
            get {
                return ResourceManager.GetString("HTML_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///                    &lt;td&gt;Report generated at:&lt;/td&gt;
        ///                    &lt;td&gt;{0}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td&gt;Allow User Root Store:&lt;/td&gt;
        ///                    &lt;td&gt;{1}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td&gt;Allowed TLS Versions:&lt;/td&gt;
        ///                    &lt;td&gt;{2}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td&gt;Weak RSA Key Check:&lt;/td&gt;
        ///                    &lt;td&gt;{3}&lt;/td&gt;
        ///                &lt;/tr&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_REPORT_META {
            get {
                return ResourceManager.GetString("HTML_REPORT_META", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAC1UlEQVR42qWTa0iTURjH/9tE58x027upaXMuNxlT00XgDfripRtioKEYCUuExVSypA8REX4wppsXCqlFmGZWkEEGZoJDiBqB5RRv09Lyks3pnDhFc1tny4bYR194OJznnOf3nv9zoWHPV3GlIpMsWcRSiEl33KPEPhDr1tZp3+2+T9sVKCSLikvxlOERAlZIaBjYwRzPmXVlGb8WfmJu9sf6kmWxibjuEtC0F7ATXCWWSC/IIqPAta2A8W0Szu/T+L21hW02Gw7iXxMdwfjcLCZMo0/I/ZtuyD9ALQm+mkxRoPp6ERglxHxjA3wPhWPL4YB9dgZBeXlwWldhzTqNL6s2N0RDANdobs3k2a/SEo+zxO/1YF9SgCkSYaGqClPV1XDABa7yMoI1GjhNJti0dVg4lQ3DsNEt55wboIlPOFYhJ2qofgMYcjn4RUUe7V9LS2FbWwP/XhMCWUxM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMG_BAD {
            get {
                return ResourceManager.GetString("IMG_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEwMPRyoQAAADZJREFUOE+lyLERACAAAyH3XzouQOGfBQ1n2xdmwSyYBbNgFsyCWTALZsEsmAWzYBbMgvlu5wLFrf0f6I7L7gAAAABJRU5ErkJggg==.
        /// </summary>
        internal static string IMG_BLANK {
            get {
                return ResourceManager.GetString("IMG_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAC1UlEQVR42qWTa0iTURjH/+82dczhZXm/pDErL1leKkUoE5tlNxVMhERNI+gi5pQEsS8GIZH2QUso/BJdTC0rlNIMJNI0qLahLTIv2bxMzXkJ9d3e913nnbbEPnrg4cA55/97znOe/6GwbigLlAlkOkQihkTQ6rKWRBeJ1sqblW1rz1NrhP5kurjJxfWct89mibuHJ5ydZJY9w+wM9BPjGNWNLP6anqohS9UENGwFrIqvbt0WlOEf4odp2TCGqV5Mcj/AMCxcTH7whBw+dCBGe0fR/017n5y/wkP+Am4QcaFvlAfU4jcYZDQwm8xgWA6MiSEQDqn+uXAReMOgW8akapqHVBBAEcXXTK7dFLY/XPLJ8SWGiHhFyIIlYhO5gVTshGx5PmLdEpHffgYHhano69bw5aTwgIqdYZFKNmwGb40NYFkWJtNKZpZAKKEAyf6ZyJTnQTXbgwvPspDs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMG_OK {
            get {
                return ResourceManager.GetString("IMG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACEElEQVR42p2STU8TURSGz51Op820tbRCCKgUME4DRg0RUUyIH4mJutDEFZE9if4CYK/wCzC6x7gzcYMLP1ZaQ9JEY6xSTRoKiFSlkUJiOx/X956phqgVw928nXvnfc4zMxXUYM3dax5EPKhfXhoY/pL5233iH4D5SCJmhWMR+lr8lAcg/d8AlM8jZtNDfaSHDMo9niMp5QVAHm4LQDmAyEV3N1kHTh7mveKrPFvgZy8g7naAq9id6TnVT+GYyXv29yq9ecQWIwDcbQhA2UC8jrcmre7jxyhozviAzSuweA+LFWVxCJBaI8A1IcR0z5l+CplhCkbv835t/TI5yuJpVllcB+DWHwCUo4hsor3F6uyzSHqSjLj/FWvli5zLbxfoc3FVWRwFZON3wJjQtMmDp/HmDR0Aj0LJWT6rls5xOrZNuWc5dTYOwNQvAMpJRKalo9Vq62zm6XCliRsF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IMG_WARN {
            get {
                return ResourceManager.GetString("IMG_WARN", resourceCulture);
            }
        }
    }
}
